### ISSUE TITLE
[feature] Add config options: skip typing generation, skip missing docstring generation

### ISSUE THREAD

**Issue by MatteoCampinoti94** [valentingol/docstripy#14]
As per the title, it would be great if there were options to configure the output more precisely.

Specifically, it would be nice to skip generating type keywords like `:type:` and `:rtype:`. They are kind of redundant when there is typing information already in the code, and can cause issues if the docstring and typing are not in sync.

Further, it would be nice to not generate new docstring for methods, functions, etc. as it can override docstrings from abstract classes.

**Comment by valentingol** [comment]
I do not see why it can actually overwrite docstrings from abstract class specifically and I would be happy to have a short example of python file that fools the module... But anyway, in version 0.7.1 you have the option to prevent the missing docstring automatic generation. You also have the possibility to prevent type hinting. Try `--noadd` and `--notype` options in command line ;)

**Comment by valentingol** [comment]
I'm closing this issue for the time being as the request has been processed. If you had a docstring overwriting problem, I encourage you to make an other issue. I've actually had quite a few similar problems in my tests when detecting docstring in some tricky cases that led to overwriting but I thought I'd sorted that out...

**Comment by MatteoCampinoti94** [comment]
It won't overwrite the actual docstring, but many IDE's use the docstring from the abstract method if the implementation does not have one.

We have this tool that needs to handle a number of different databases, and while each of the handler classes has a different behaviour in the background, they implement the same abstract methods and return the same objects. Copying the same docstring over and over would just lead to us forgetting to update them when/if the abstract method changes, so we leave the implementations empty.

**Comment by valentingol** [comment]
Ok interesting!
